name: Code Review
on:
  pull_request_target:
    types:
      - opened      # PR 创建时触发
      - reopened    # PR 重新打开时触发
      - synchronize # PR 有新提交时触发

permissions:
  pull-requests: write

jobs:
  setup-deepseek-review:
    runs-on: macos-latest
    name: Code Review
    steps:
      - name: DeepSeek Code Review
        uses: hustcer/deepseek-review@v1
        with:
          chat-token: ${{ secrets.CHAT_TOKEN }}
